### PR TITLE
fix valid_time vs time dimension name for plot_region_all()

### PR DESCRIPTION
**Pull request by thomaszwagerman**
See #23

### CODE REVIEW

**Comment by thomaszwagerman** [comment]
this works - now need a solution for `plot_region_year()`

**Comment by thomaszwagerman** [comment]
Summary of changes, closes #23. Tests passed (some warnings on pkg deprecations but not branch-specific) and no changes to /docs.

### Losing date values
All date values were being dropped when converting self.raw_msl_data to self.masked_msl_data, when filtered against the lsm MASK_THRESHOLD. 

Changing:

```python
self.land_sea_mask < MASK_THRESHOLD
```
to

```python
self.land_sea_mask.values < MASK_THRESHOLD
```
Retains date values [(20240101, 20240202)] instead of [(0, 1)] etc

### Error plotting calculation dataframe

`self.asl_df` failed to plot as the number of header lines was incorrect, so column names were not read in. Changed from 27 to 28. I wonder what caused that change and I wonder if this merits more investigating.

### variable names 'time', 'valid_time', 'date'

Several instances where plotting functions where looking for 'time' when this should have been 'valid_time' (I suspect divergence introduced after ERA5T filtering). Another instance where `get_lows()` was expecting 'date' but should have been 'time'.

### hard-coded indexing

In `plot.py` there was hard-coded indexing which I've removed in favour of matching the index to the date that is being iterated on.

**Review by davidwyld — APPROVED** [review]
Simply marvellous! Sorry if you were waiting for a review from me, feel free to poke any time.

I suspect that many of these points stem from the irksome restructuring of the data from CDS and others are from my stupidity.

Thanks for sorting. Do you need me to merge or do you have permissions?

**Comment by thomaszwagerman** [comment]
No worries - I only just finished it so was certainly not waiting!

I think probably all data restructuring from CDS, haha! 

I'm happy to merge :100:

**Pull request merged**
